name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: npm install
        run: |
          npm install

      - name: rebuild midi module
        run: |
          npm run rebuild:test

      - name: npm test
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

        run: |
          npm run package
          npm run lint
          npm exec tsc
          npm test
